services:
  postgres:
    image: postgres:16-alpine
    container_name: fragrance_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fragrance
      POSTGRES_PASSWORD: fragrance
      POSTGRES_DB: fragrance_dev
    ports:
      - "5432:5432"
    volumes:
      - fragrance_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: fragrance_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fodubai.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  fragrance_postgres_data: